# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>
  username: root
  password: password
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  reconnect: false
  database: historymap_development

test:
  <<: *default
  reconnect: false
  database: historymap_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
